### PR TITLE
Updated windows to support the `speed` parameter. 

### PR DESCRIPTION
**Pull request by JimmyBoh**
This PR fixes part of Marak/say.js#46. This adds support for specifying `speed` on Windows.

On Windows the acceptable values range from -10 to +10, with zero meaning no change. From the tests on my machine this scale is logarithmic and not linear, so the logic used on the other platforms doesn't directly transfer. I ran quite a few tests and used some basic maths to figure out the best conversion equation. It could differ per machine, but my results show that windows can only modify the playback speed from x0.4 up to x3. If any provided speed falls outside of the supported range the speed is simply clamped (never greater than 10 or less than -10).

I will be posting the data I collected for historical purposes.

### CODE REVIEW

**Comment by JimmyBoh** [comment]
To determine how `[-10,+10]` maps to playback rate I ran the following test: Foreach value from -10 to +10 execute the say command 10 sequential times using the opening crawl. Record the time and compute the average time per speed, then use the average times to calculate the approximate rate.

Attached is an Excel document containing the recorded data and expected outputs based on speed inputs. For those without Excel here is a pretty screenshot:

image

**Comment by JimmyBoh** [comment]
Sorry, accidentally added an extra feature to the PR.

**Comment by tlhunter** [comment]
This looks great! Thanks for the contribution.

**Comment by tlhunter** [comment]
Published in **v0.14.0**.

**Pull request merged**
